default:
  bucket: cumulus-test-sandbox-internal
  apiUsername: jasmine

cumulus-sit:
  bucket: cumulus-sit-internal
  apiUsername: jasmine

mvd-tf:
  bucket: mvd-internal

mvd-dev-tf:
  bucket: mvd-internal

jl-tf:
  bucket: jl-test-integration-internal

kk-tf:
  bucket: kk-tf-internal

lf-test-tf:
  bucket: lf-internal

mth-ci-tf:
  bucket: mth-internal

mth-dev-tf:
  bucket: mth-internal

lpf-tf:
  bucket: lf-internal

mhs3:
  bucket: mhs3-internal

mhs2:
  bucket: mhs2-internal

bt-tf:
  bucket: bt-internal
